name: Proxy prod build
on:
  push:
    tags:
      - '*'
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Proxy build and push
        uses: docker/build-push-action@v2
        with:
          context: proxy
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/proxy
